DROP DATABASE IF EXISTS CONTROLE_INVENTARIO;
CREATE DATABASE CONTROLE_INVENTARIO;
USE CONTROLE_INVENTARIO;

CREATE TABLE USUARIO (
    ID INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(255) NOT NULL,
    LOGIN VARCHAR(255) NOT NULL,
    SENHA VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(8),
    EMAIL VARCHAR(320),
    -- 1 Padrão 2 Gestor    
    NIVEL_PERMISSAO INT NOT NULL,
    PRIMARY KEY (ID , LOGIN)
);

CREATE TABLE SETOR (
    ID INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(255),
    PRIMARY KEY (ID)
);

CREATE TABLE CATEGORIA (
    ID INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(255),
    PRIMARY KEY (ID)
);

CREATE TABLE PATRIMONIO (
    ID INT NOT NULL AUTO_INCREMENT,
    ID_CATEGORIA INT NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    QUANTIDADE DOUBLE,
    PRIMARY KEY (ID),
    FOREIGN KEY (ID_CATEGORIA)
        REFERENCES CATEGORIA (ID)
);

CREATE TABLE ITEM (
    ID INT NOT NULL AUTO_INCREMENT,
    ID_PATRIMONIO INT NOT NULL,
    ID_SETOR INT NOT NULL,
    ESTADO INT NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (ID_SETOR)
        REFERENCES SETOR (ID)
);

CREATE TABLE HISTORICO_MOVIMENTACAO (
    ID INT NOT NULL AUTO_INCREMENT,
    ID_USUARIO INT NOT NULL,
    ID_SETOR INT NOT NULL,
    ID_ITEM INT NOT NULL,
    DATA_RETIRADA DATETIME NOT NULL,
    DATA_DEVOLUCAO DATETIME,
    FOREIGN KEY (ID_USUARIO)
        REFERENCES USUARIO (ID),
    FOREIGN KEY (ID_SETOR)
        REFERENCES SETOR (ID),
    FOREIGN KEY (ID_ITEM)
        REFERENCES ITEM (ID),
    PRIMARY KEY (ID)
);

INSERT INTO `usuario` (`ID`, `NOME`, `LOGIN`, `SENHA`, `TELEFONE`, `EMAIL`, `NIVEL_PERMISSAO`) VALUES (NULL, 'Rafael', 'rafaalberto', '123456', NULL, NULL, '2');